# Generated by Django 3.1 on 2021-10-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('code', models.CharField(default='', max_length=100, verbose_name='Code')),
                ('population', models.CharField(default='', max_length=100, verbose_name='Population')),
            ],
            options={
                'verbose_name': 'Countries',
            },
        ),
    ]
