# Generated by Django 3.1 on 2021-10-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
